environment:
  host: '[::]'
  port: 8061
server_variables:
  model_dir: model
  logs_dir: logs
  weights: density_estimator_model.pth
  log_level: INFO
  img_output_dim: [640, 640]
  metadata_dir: metadata
  # roi: roi.json
